# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s="Hi there Sam!"
n=s.split()
print(n)

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [13]:
s="The diameter of {} is {} kilometers"
s.format("Earth",12742)

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

# Numpy

In [5]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
a=np.zeros((2,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
a=np.ones((2,5))
b=a*5
b

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

## 5. Create an array of all the even integers from 20 to 35

In [15]:
for x in range(20,35):
  if x%2==0:
    print(x)

20
22
24
26
28
30
32
34

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
a=np.mat("0,1,2;3,4,5;6,7,8")
a

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd

In [20]:
lst=[[10,20,30,40,50],[25,35,45,55,65],[75,85,95,105,125]]
df=pd.DataFrame(lst)
df

    0   1   2    3    4
0  10  20  30   40   50
1  25  35  45   55   65
2  75  85  95  105  125

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
pd.date_range("01-01-2023","10-02-2023")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [21]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [22]:
df=pd.DataFrame(lists)
df

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24